apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  annotations:
    client.lifecycle.config.k8s.io/mutation: ignore
  labels:
    app: sidecar-injector
    install.operator.istio.io/owning-resource: unknown
    install.operator.istio.io/owning-resource-namespace: istio-system
    istio.io/rev: asm-1182-4
    operator.istio.io/component: Pilot
    operator.istio.io/managed: Reconcile
    operator.istio.io/version: 1.18.2-asm.4
    release: istio
  name: istio-sidecar-injector-asm-1182-4
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMVENDQXBXZ0F3SUJBZ0lSQUpIc0JPSlM4UysyRGNGRDhaUS9NeVF3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa1lUazBaV0ZsTkdJdE9XVmpPUzAwWmpFM0xXSmtaall0Wm1abVpqWXhORFV6TURWawpNQ0FYRFRJek1Ea3lPREU0TURNeE9Wb1lEekl3TlRNd09USXdNVGt3TXpFNVdqQXZNUzB3S3dZRFZRUURFeVJoCk9UUmxZV1UwWWkwNVpXTTVMVFJtTVRjdFltUm1OaTFtWm1abU5qRTBOVE13TldRd2dnR2lNQTBHQ1NxR1NJYjMKRFFFQkFRVUFBNElCandBd2dnR0tBb0lCZ1FDcFNQOVZsaEZHL3FkUGpvbUpRdUJqYkNoc25CMDczUHlXMEZjNwp5RVIvbDNnclMreEVyV21ISG55L0JiUW1YSGdCQTltVVA0TXZxa3YwYkFDK2hwM1NGeGtnUGJwWHJWbEdFNm1JCkxoMEVRaWl5MTF6V08wMzJENHJMMXhpTURJQXl5bG9UR3QrZ2FVbEVZbGc4cmdJVVVxeHFWUE9sa2hDa0FEUy8KNkZ1bGdVaUhBWkZrN0liakdpQ3VsbERhdFpNd0s0Y05lQU1kWW5EdFZwZkpTOWppdzNNNHFLV05lbTB4a0lDagpoQ2JNL0JuZHZibFZmMzdmUFNmSXFWQ2ZTdGJLNXlsNzFWYWRGdVVDOXZjRHNGNmpFWUVFbXI5ZmRrU0UrTSszCkFSMHp1ZTYyOHg1cmNYT0JKWXFDcTlKUCtoS3MzTklhazltU0lHelB6MkJvSCtlNGFQdEJUOEdXYUtQbEhzNkwKOVczL215TUVsQ2Rtc0N5SUVONW44RTV4QWh4RkxLekY4ZTFpRDBnNDBkUGdUY2MzWEhpbXVGSFFVK2ZmVE1wMQpacTAwelp0bWw2bjVmK0U4cW11MVozNHJMcjg1cU0vblEwWnd0UkxadWt5N0M4TWJaaEI4a1VkVlc3TkNqcWhyCmdTazlJbzhLTVNxTUdTcTNCNjloNjVIUmZGMENBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdJRU1BOEcKQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGTEl0L1hRVkgvSGNUNnFnejNYaktnUHhWcFNvTUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQmdRQmxYMGhza0dtRW5WWjljQUtJNzY2OEo2TDQ3Z2pvYmJmM1YyREpSN3g3Cm8wd0N0VEx2aTRoWW5oRVNuZFlaeDBhemxRbDg5YXhZV0dKSXA1TFhUYi90K3BuSFBRdXliTWp0Q0k1QU8ybU8KTjQzNGF1TVZickxsMUp1RTZ6aVh6QUMyN2hZTlpNTEJKMHhIQU0wbWZpN0ZnV3NvS3d1cVNhdVVEQUxvYkEvQgp6SlVZZFJkT1pjanhsSHNmQXR3eXJaWWNsSkdYdm5vT2VyOWlGeEJqZDlFMXJRNGowQ3hLZlEvVEh3ME5ZS2pOCmc0Y3JTLzlaM05yNEwrMHBVdGFpdWtUK3BKTTdPNUVxL1RNQXlSYk12NmxnYXgrL3h3T2JGN1hBdnBRS0dhMHQKYXd5UE5KOEZxemg0NlBDeGd0MkZoQzBRWXB4WXM2ekpUOVpkNmZ1TEMyempOQlR4aTNjb284ZVZzRzZFODNNVQpIVCs0anlOS083a1ZwRzJqWG9VaEFTWHpxZmg5YnkvZDA4M2w2WER1eFFBSHN2NkQvaUh2RWFaRy81bXN3ZWVhClAxSEJQeTQ3R1VtdUtxUUx5K283ZTBxTVhhK3VuTE0rbWJMQU5sRERnSjdWYW94RCtad3AzMXU5NlUzbWhaeC8KY3NacU0rR0tNaUhJT2MzcEg2MEFoOWM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: istiod-asm-1182-4
      namespace: istio-system
      path: /inject
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: rev.namespace.sidecar-injector.istio.io
  namespaceSelector:
    matchExpressions:
    - key: istio.io/rev
      operator: In
      values:
      - asm-1182-4
    - key: istio-injection
      operator: DoesNotExist
  objectSelector:
    matchExpressions:
    - key: sidecar.istio.io/inject
      operator: NotIn
      values:
      - "false"
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMVENDQXBXZ0F3SUJBZ0lSQUpIc0JPSlM4UysyRGNGRDhaUS9NeVF3RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa1lUazBaV0ZsTkdJdE9XVmpPUzAwWmpFM0xXSmtaall0Wm1abVpqWXhORFV6TURWawpNQ0FYRFRJek1Ea3lPREU0TURNeE9Wb1lEekl3TlRNd09USXdNVGt3TXpFNVdqQXZNUzB3S3dZRFZRUURFeVJoCk9UUmxZV1UwWWkwNVpXTTVMVFJtTVRjdFltUm1OaTFtWm1abU5qRTBOVE13TldRd2dnR2lNQTBHQ1NxR1NJYjMKRFFFQkFRVUFBNElCandBd2dnR0tBb0lCZ1FDcFNQOVZsaEZHL3FkUGpvbUpRdUJqYkNoc25CMDczUHlXMEZjNwp5RVIvbDNnclMreEVyV21ISG55L0JiUW1YSGdCQTltVVA0TXZxa3YwYkFDK2hwM1NGeGtnUGJwWHJWbEdFNm1JCkxoMEVRaWl5MTF6V08wMzJENHJMMXhpTURJQXl5bG9UR3QrZ2FVbEVZbGc4cmdJVVVxeHFWUE9sa2hDa0FEUy8KNkZ1bGdVaUhBWkZrN0liakdpQ3VsbERhdFpNd0s0Y05lQU1kWW5EdFZwZkpTOWppdzNNNHFLV05lbTB4a0lDagpoQ2JNL0JuZHZibFZmMzdmUFNmSXFWQ2ZTdGJLNXlsNzFWYWRGdVVDOXZjRHNGNmpFWUVFbXI5ZmRrU0UrTSszCkFSMHp1ZTYyOHg1cmNYT0JKWXFDcTlKUCtoS3MzTklhazltU0lHelB6MkJvSCtlNGFQdEJUOEdXYUtQbEhzNkwKOVczL215TUVsQ2Rtc0N5SUVONW44RTV4QWh4RkxLekY4ZTFpRDBnNDBkUGdUY2MzWEhpbXVGSFFVK2ZmVE1wMQpacTAwelp0bWw2bjVmK0U4cW11MVozNHJMcjg1cU0vblEwWnd0UkxadWt5N0M4TWJaaEI4a1VkVlc3TkNqcWhyCmdTazlJbzhLTVNxTUdTcTNCNjloNjVIUmZGMENBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdJRU1BOEcKQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGTEl0L1hRVkgvSGNUNnFnejNYaktnUHhWcFNvTUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQmdRQmxYMGhza0dtRW5WWjljQUtJNzY2OEo2TDQ3Z2pvYmJmM1YyREpSN3g3Cm8wd0N0VEx2aTRoWW5oRVNuZFlaeDBhemxRbDg5YXhZV0dKSXA1TFhUYi90K3BuSFBRdXliTWp0Q0k1QU8ybU8KTjQzNGF1TVZickxsMUp1RTZ6aVh6QUMyN2hZTlpNTEJKMHhIQU0wbWZpN0ZnV3NvS3d1cVNhdVVEQUxvYkEvQgp6SlVZZFJkT1pjanhsSHNmQXR3eXJaWWNsSkdYdm5vT2VyOWlGeEJqZDlFMXJRNGowQ3hLZlEvVEh3ME5ZS2pOCmc0Y3JTLzlaM05yNEwrMHBVdGFpdWtUK3BKTTdPNUVxL1RNQXlSYk12NmxnYXgrL3h3T2JGN1hBdnBRS0dhMHQKYXd5UE5KOEZxemg0NlBDeGd0MkZoQzBRWXB4WXM2ekpUOVpkNmZ1TEMyempOQlR4aTNjb284ZVZzRzZFODNNVQpIVCs0anlOS083a1ZwRzJqWG9VaEFTWHpxZmg5YnkvZDA4M2w2WER1eFFBSHN2NkQvaUh2RWFaRy81bXN3ZWVhClAxSEJQeTQ3R1VtdUtxUUx5K283ZTBxTVhhK3VuTE0rbWJMQU5sRERnSjdWYW94RCtad3AzMXU5NlUzbWhaeC8KY3NacU0rR0tNaUhJT2MzcEg2MEFoOWM9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    service:
      name: istiod-asm-1182-4
      namespace: istio-system
      path: /inject
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: rev.object.sidecar-injector.istio.io
  namespaceSelector:
    matchExpressions:
    - key: istio.io/rev
      operator: DoesNotExist
    - key: istio-injection
      operator: DoesNotExist
  objectSelector:
    matchExpressions:
    - key: sidecar.istio.io/inject
      operator: NotIn
      values:
      - "false"
    - key: istio.io/rev
      operator: In
      values:
      - asm-1182-4
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
