apiVersion: v1
items:
- apiVersion: policy/v1
  kind: PodDisruptionBudget
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"policy/v1","kind":"PodDisruptionBudget","metadata":{"annotations":{},"labels":{"app":"istiod","install.operator.istio.io/owning-resource":"unknown","install.operator.istio.io/owning-resource-namespace":"istio-system","istio":"pilot","istio.io/rev":"asm-1182-4","operator.istio.io/component":"Pilot","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.18.2-asm.4","release":"istio"},"name":"istiod-asm-1182-4","namespace":"istio-system"},"spec":{"minAvailable":1,"selector":{"matchLabels":{"app":"istiod","istio.io/rev":"asm-1182-4"}}}}
    creationTimestamp: "2023-09-28T21:01:42Z"
    generation: 1
    labels:
      app: istiod
      install.operator.istio.io/owning-resource: unknown
      install.operator.istio.io/owning-resource-namespace: istio-system
      istio: pilot
      istio.io/rev: asm-1182-4
      operator.istio.io/component: Pilot
      operator.istio.io/managed: Reconcile
      operator.istio.io/version: 1.18.2-asm.4
      release: istio
    name: istiod-asm-1182-4
    namespace: istio-system
    resourceVersion: "75566"
    uid: 4683cd38-71e8-443b-b3ee-f93ec18e7919
  spec:
    minAvailable: 1
    selector:
      matchLabels:
        app: istiod
        istio.io/rev: asm-1182-4
  status:
    conditions:
    - lastTransitionTime: "2023-09-28T21:02:03Z"
      message: ""
      observedGeneration: 1
      reason: SufficientPods
      status: "True"
      type: DisruptionAllowed
    currentHealthy: 2
    desiredHealthy: 1
    disruptionsAllowed: 1
    expectedPods: 2
    observedGeneration: 1
kind: List
metadata:
  resourceVersion: ""
