apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"app":"istiod","install.operator.istio.io/owning-resource-namespace":"istio-system","istio.io/rev":"asm-1182-4","operator.istio.io/component":"Pilot","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.18.2-asm.4","release":"istio"},"name":"istiod-asm-1182-4","namespace":"istio-system"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"istiod-asm-1182-4"},"subjects":[{"kind":"ServiceAccount","name":"istiod-asm-1182-4","namespace":"istio-system"}]}
    labels:
      app: istiod
      install.operator.istio.io/owning-resource-namespace: istio-system
      istio.io/rev: asm-1182-4
      operator.istio.io/component: Pilot
      operator.istio.io/managed: Reconcile
      operator.istio.io/version: 1.18.2-asm.4
      release: istio
    name: istiod-asm-1182-4
    namespace: istio-system
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: istiod-asm-1182-4
  subjects:
  - kind: ServiceAccount
    name: istiod-asm-1182-4
    namespace: istio-system
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"RoleBinding","metadata":{"annotations":{},"labels":{"app":"istiod","install.operator.istio.io/owning-resource-namespace":"istio-system","istio.io/rev":"asm-1182-4","operator.istio.io/component":"Base","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.18.2-asm.4","release":"istio"},"name":"istiod-istio-system","namespace":"istio-system"},"roleRef":{"apiGroup":"rbac.authorization.k8s.io","kind":"Role","name":"istiod-istio-system"},"subjects":[{"kind":"ServiceAccount","name":"istiod-service-account","namespace":"istio-system"}]}
    labels:
      app: istiod
      install.operator.istio.io/owning-resource-namespace: istio-system
      istio.io/rev: asm-1182-4
      operator.istio.io/component: Base
      operator.istio.io/managed: Reconcile
      operator.istio.io/version: 1.18.2-asm.4
      release: istio
    name: istiod-istio-system
    namespace: istio-system
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: istiod-istio-system
  subjects:
  - kind: ServiceAccount
    name: istiod-service-account
    namespace: istio-system
kind: List
metadata:
  resourceVersion: ""
