apiVersion: v1
items:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"labels":{"app":"istiod","install.operator.istio.io/owning-resource-namespace":"istio-system","istio.io/rev":"asm-1182-4","operator.istio.io/component":"Pilot","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.18.2-asm.4","release":"istio"},"name":"istiod-asm-1182-4","namespace":"istio-system"},"rules":[{"apiGroups":["networking.istio.io"],"resources":["gateways"],"verbs":["create"]},{"apiGroups":[""],"resources":["secrets"],"verbs":["create","get","watch","list","update","delete"]},{"apiGroups":[""],"resources":["configmaps"],"verbs":["delete"]},{"apiGroups":["coordination.k8s.io"],"resources":["leases"],"verbs":["get","update","patch","create"]}]}
    labels:
      app: istiod
      install.operator.istio.io/owning-resource-namespace: istio-system
      istio.io/rev: asm-1182-4
      operator.istio.io/component: Pilot
      operator.istio.io/managed: Reconcile
      operator.istio.io/version: 1.18.2-asm.4
      release: istio
    name: istiod-asm-1182-4
    namespace: istio-system
  rules:
  - apiGroups:
    - networking.istio.io
    resources:
    - gateways
    verbs:
    - create
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - create
    - get
    - watch
    - list
    - update
    - delete
  - apiGroups:
    - ""
    resources:
    - configmaps
    verbs:
    - delete
  - apiGroups:
    - coordination.k8s.io
    resources:
    - leases
    verbs:
    - get
    - update
    - patch
    - create
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"rbac.authorization.k8s.io/v1","kind":"Role","metadata":{"annotations":{},"labels":{"app":"istiod","install.operator.istio.io/owning-resource-namespace":"istio-system","istio.io/rev":"asm-1182-4","operator.istio.io/component":"Base","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.18.2-asm.4","release":"istio"},"name":"istiod-istio-system","namespace":"istio-system"},"rules":[{"apiGroups":["networking.istio.io"],"resources":["gateways"],"verbs":["create"]},{"apiGroups":[""],"resources":["secrets"],"verbs":["create","get","watch","list","update","delete"]}]}
    labels:
      app: istiod
      install.operator.istio.io/owning-resource-namespace: istio-system
      istio.io/rev: asm-1182-4
      operator.istio.io/component: Base
      operator.istio.io/managed: Reconcile
      operator.istio.io/version: 1.18.2-asm.4
      release: istio
    name: istiod-istio-system
    namespace: istio-system
  rules:
  - apiGroups:
    - networking.istio.io
    resources:
    - gateways
    verbs:
    - create
  - apiGroups:
    - ""
    resources:
    - secrets
    verbs:
    - create
    - get
    - watch
    - list
    - update
    - delete
kind: List
metadata:
  resourceVersion: ""
