apiVersion: v1
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app":"istio-reader","install.operator.istio.io/owning-resource-namespace":"istio-system","istio.io/rev":"asm-1182-4","operator.istio.io/component":"Base","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.18.2-asm.4","release":"istio"},"name":"istio-reader-service-account","namespace":"istio-system"}}
    labels:
      app: istio-reader
      install.operator.istio.io/owning-resource-namespace: istio-system
      istio.io/rev: asm-1182-4
      operator.istio.io/component: Base
      operator.istio.io/managed: Reconcile
      operator.istio.io/version: 1.18.2-asm.4
      release: istio
    name: istio-reader-service-account
    namespace: istio-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app":"istiod","install.operator.istio.io/owning-resource-namespace":"istio-system","istio.io/rev":"asm-1182-4","operator.istio.io/component":"Pilot","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.18.2-asm.4","release":"istio"},"name":"istiod-asm-1182-4","namespace":"istio-system"}}
    labels:
      app: istiod
      install.operator.istio.io/owning-resource-namespace: istio-system
      istio.io/rev: asm-1182-4
      operator.istio.io/component: Pilot
      operator.istio.io/managed: Reconcile
      operator.istio.io/version: 1.18.2-asm.4
      release: istio
    name: istiod-asm-1182-4
    namespace: istio-system
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"ServiceAccount","metadata":{"annotations":{},"labels":{"app":"istiod","install.operator.istio.io/owning-resource-namespace":"istio-system","istio.io/rev":"asm-1182-4","operator.istio.io/component":"Base","operator.istio.io/managed":"Reconcile","operator.istio.io/version":"1.18.2-asm.4","release":"istio"},"name":"istiod-service-account","namespace":"istio-system"}}
    labels:
      app: istiod
      install.operator.istio.io/owning-resource-namespace: istio-system
      istio.io/rev: asm-1182-4
      operator.istio.io/component: Base
      operator.istio.io/managed: Reconcile
      operator.istio.io/version: 1.18.2-asm.4
      release: istio
    name: istiod-service-account
    namespace: istio-system
kind: List
metadata:
  resourceVersion: ""
