apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: asm-gcp-multiproject
  meshConfig:
    trustDomainAliases: # {"$ref":"#/definitions/io.k8s.cli.setters.anthos.servicemesh.trustDomainAliases"}
    - "svc-gcp-d349.svc.id.goog"
    - "svc-gcp-d349.hub.id.goog"
  values:
    global:
      meshID: "proj-114188760578" # {"$ref":"#/definitions/io.k8s.cli.substitutions.mesh-id"}
