apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  values:
    global:
      multiCluster:
        # Provided to ensure a human readable name rather than a UUID.
        clusterName: "cn-svc-gcp-d349-us-east4-svc-demo" # {"$ref":"#/definitions/io.k8s.cli.substitutions.cluster-name"}
